var options = [
	'Try to look at your brain.',
	'See how many times in a row you can flip a bottle.',
	'See how long it takes for your computer to boot up.',
	'Read a Book.',
	'Watch some TV.',
	'Drink a glass of water.',
	'Make a Pillow Fort.',
	'Play a Board Game.',
	'Play a Video Game.',
	'Plant a tree/flower.',
	'Jump in a cab and scream "Follow that car!".',
	'Practice frontflipping.',
	'Do a puzzle.',
	'Go to Walmart and ask if you can buy a wall.',
	'Send a postcard to your friend.',
	'Make some food.',
	'Learn a new language',
	'Do your homework.',
	'Play games with your friends(if you have any).',
	'Play some timewasting games on Y8.com',
	'Write a Story.',
	'Clean up your computer.',
	'Do your laundry.',
	'Create a website.',
	'Make a bucket list.',
	'Make a slingshot out of things, you found in your house.',
	'Masturbate.',
	'Play with your pet.',
	'Try to swallow your tongue.',
	'Stare a person in the neck until he turns around.',
	'Do a sport.',
	'Go on vacation.',
	'Go to the nearest swimming halll.',
	'Call a friend.',
	'Make a lemonade stand.',
	'Look your name up in Urban Dictionary.',
	'Listen to some good music.',
	'Take a bubble bath.',
	'Learn a magic trick.',
	'Sleep.',
	'Torture Siri.',
	'Pretend your Spiderman.',
	'Draw.',
	'Hack people.',
	'Enter the Dark Web.',
	'Scream at people that "But im a cow!',
	'Go insane.',
	'Take a shit.',
	'Climb a tree.',
	'Go for a run.',
	'Browse WikiHow.com',
	'Throw a party.',
	'Repaint your walls.',
	'Be offensive to someone.',
	'Secret Message: Gains',
	'Secret Message: Tooth Fairy',
	'Secret Message: Horse',
]

function newQuote()
{
	var randomNumber = Math.floor(Math.random() * (options.length));
	document.getElementById('u128-4').innerHTML = options[randomNumber];
}
